/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class Ablak extends javax.swing.JFrame {

    /**
     * Creates new form Ablak
     */
    public Ablak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jBPohar1 = new javax.swing.JButton();
        jBPohar2 = new javax.swing.JButton();
        jBPohar3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCBGolyo = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jFajl = new javax.swing.JMenu();
        Mentes = new javax.swing.JMenuItem();
        Betoltes = new javax.swing.JMenuItem();
        Uj = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        Harom = new javax.swing.JMenuItem();
        Negy = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Itt a piros...\"");

        jBPohar1.setText("Pohár1");

        jBPohar2.setText("Pohár2");

        jBPohar3.setText("jButton3");

        jLabel1.setText("Talált(igen/nem): ");

        jCBGolyo.setText("Tippelésenként a golyó legyen új helyen");

        jMenu.setText("Menu");

        jFajl.setText("Fájl");

        Mentes.setText("Mentés");
        jFajl.add(Mentes);

        Betoltes.setText("Betöltés");
        Betoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetoltesActionPerformed(evt);
            }
        });
        jFajl.add(Betoltes);

        jMenu.add(jFajl);

        Uj.setText("Játék");
        Uj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UjMouseClicked(evt);
            }
        });

        jMenuItem5.setText("Új játék");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Uj.add(jMenuItem5);

        Harom.setText("3 pohár");
        Harom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaromActionPerformed(evt);
            }
        });
        Uj.add(Harom);

        Negy.setText("4 pohár");
        Negy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegyActionPerformed(evt);
            }
        });
        Uj.add(Negy);

        jMenu.add(Uj);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBGolyo)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jBPohar1)
                        .addGap(63, 63, 63)
                        .addComponent(jBPohar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jBPohar3)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPohar1)
                    .addComponent(jBPohar2)
                    .addComponent(jBPohar3))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jCBGolyo)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void HaromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaromActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HaromActionPerformed

    private void NegyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegyActionPerformed
        // TODO add your handling code here:
//        System.out.println("Ez a mód nem elérhető!");
       
           JOptionPane.showMessageDialog(this, "Ez a mód jelenleg nem elérhető!");
      
    }//GEN-LAST:event_NegyActionPerformed

    private void BetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetoltesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BetoltesActionPerformed

    private void UjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UjMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UjMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Betoltes;
    private javax.swing.JMenuItem Harom;
    private javax.swing.JMenuItem Mentes;
    private javax.swing.JMenuItem Negy;
    private javax.swing.JMenu Uj;
    private javax.swing.JButton jBPohar1;
    private javax.swing.JButton jBPohar2;
    private javax.swing.JButton jBPohar3;
    private javax.swing.JCheckBox jCBGolyo;
    private javax.swing.JMenu jFajl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
